name: CD — Deploy

# Se déclenche seulement sur push dans main
# après que CI soit passé
on:
  push:
    branches: [ main ]

jobs:

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build et push les images Docker sur Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build et push image backend
      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./TaskFlow.API
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/taskflow-api:latest

      # Build et push image frontend
      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./taskflow-client
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/taskflow-frontend:latest

      # Notifie que le déploiement est terminé
      - name: Notify deployment
        run: echo "✅ Deployment complete !"