name: CD — Deploy

# Se déclenche seulement quand CI est terminé avec succès
on:
  workflow_run:
    workflows: ["CI — Build & Test"]  # nom exact du CI
    types:
      - completed
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    # Vérifie que CI a réussi avant de déployer
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./TaskFlow.API
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/taskflow-api:latest

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./taskflow-client
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/taskflow-frontend:latest

      - name: Notify deployment
        run: echo "✅ Deployment complete !"